### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by PirataGu** [AdvancedPlugins/Seasons#188]
### Describe the bug

It appeared on my console. Probably while loading some chunks

### How to reproduce

idk

### Server Log

https://mcpaste.io/991e4802125c0ea1

**Comment by Ynverxe** [comment]
When it comes to chunk issues it's difficult to know what's the problem. I think the plugin is trying to get a chunk that isn't loaded and that causes a deadlock, so I will make a solution for this hypothesis. Anyways, you're using 1.20.4 or 1.20.3 so you're 5-6 versions outdated, and maybe your problem is solved in a more recent version.
