### ISSUE TITLE
Mangrove swamp biome issue which effects villagers

### ISSUE THREAD

**Issue by thewickening** [AdvancedPlugins/Seasons#72]
### Describe the bug

The swamp villager requires a true "swamp" biome in order to obtain mending. 

Seasons is redefining the "swamp"  biome to be a "mangrove swamp" which prevents the villager from becoming the proper variant when bred.

Is their a way to fix this?

Also not sure if there would be a similar issue with any other biomes. I do not have any plugins altering biomes or world gen.

The swamp was actually mislabeled as mangrove swamp, which we know for two reasons:

The land generation was that of a regular swamp, and not of a mangrove swamp.
Removing the plugin from the server, reverted the biomes as they were originally, meaning the mangrove swamp returned to being a normal swamp.

### How to reproduce

simply disable the plugin while standing in a swamp biome. You will see it is a mangrove while the plugin is enabled, when removed it shows up as a normal swamp like it should.

**Comment by GC-spigot** [comment]
It's a visual change with packets intercepting when player data is being sent from server to player. There is no change on the real world or server. This does not affect villagers at all. That is why disabling the plugin will make the real biomes re-appear, because it's only visual - nothing is ever changed :)
